package com.anthunt.aws.spring.boot.xray.config;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import com.amazonaws.xray.sql.TracingConnection;

public class AWSXRayTracingConnection extends TracingConnection {

	public AWSXRayTracingConnection(Connection connection) {
		super(connection);
	}
	
    /**
     * Call {@code connection = TracingConnection.decorate(connection)} to decorate your {@link Connection} before any calls
     * to #createStatement, #prepareStatement or #prepareCall in order to have all your SQL queries recorded with an X-Ray Subsegment.
     *
     * @param connection the connection to decorate
     * @return a {@link Connection} that traces all SQL queries in X-Ray
     */
    public static Connection decorate(Connection connection) {
        return new AWSXRayTracingConnection(connection);
    }

    @Override
    public Statement createStatement() throws SQLException {
        return AWSXRayTracingStatement.decorateStatement(delegate.createStatement());
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return AWSXRayTracingStatement.decorateStatement(delegate.createStatement(resultSetType, resultSetConcurrency));
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return AWSXRayTracingStatement.decorateStatement(delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability));
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return AWSXRayTracingStatement.decoratePreparedStatement(delegate.prepareStatement(sql), sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return AWSXRayTracingStatement.decoratePreparedStatement(delegate.prepareStatement(sql, autoGeneratedKeys), sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return AWSXRayTracingStatement.decoratePreparedStatement(delegate.prepareStatement(sql, columnIndexes), sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return AWSXRayTracingStatement.decoratePreparedStatement(delegate.prepareStatement(sql, columnNames), sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return AWSXRayTracingStatement.decoratePreparedStatement(delegate.prepareStatement(sql, resultSetType, resultSetConcurrency), sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return AWSXRayTracingStatement.decoratePreparedStatement(delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), sql);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        return AWSXRayTracingStatement.decorateCallableStatement(delegate.prepareCall(sql), sql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return AWSXRayTracingStatement.decorateCallableStatement(delegate.prepareCall(sql, resultSetType, resultSetConcurrency), sql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return AWSXRayTracingStatement.decorateCallableStatement(delegate.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability), sql);
    }

}
